[package]
name = "cdy"
version = "0.1.0"
authors = ["Aleksey Kliger <alklig@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
